# Generated by Django 6.0.5 on 2026-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='allow_public_edit',
            field=models.BooleanField(default=False, help_text='Personen mit Link dürfen Einträge hinzufügen/ändern'),
        ),
    ]
