# Generated by Django 6.0.5 on 2026-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bucketlist_allow_public_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
