# Generated by Django 6.0.5 on 2026-05-16 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_created_by_listitem_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#00d2ff', max_length=7)),
                ('accent_color', models.CharField(default='#ffab00', max_length=7)),
                ('bg_color', models.CharField(default='#0a0e14', max_length=7)),
                ('glass_opacity', models.DecimalField(decimal_places=2, default=0.15, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
