# Generated by Django 6.0.5 on 2026-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
