# Generated by Django 6.0.5 on 2026-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersetting_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='guest_created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='guest_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
