# Generated by Django 6.0.5 on 2026-05-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listitem_guest_created_by_listitem_guest_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='input_bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='input_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
