# Generated by Django 6.0.5 on 2026-05-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usersetting_input_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='involved_persons',
        ),
        migrations.CreateModel(
            name='ItemPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assigned', 'Zuständig'), ('invited', 'Eingeladen'), ('attending', 'Zugesagt'), ('declined', 'Abgesagt'), ('maybe', 'Vielleicht')], default='assigned', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='core.listitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_roles', to='core.person')),
            ],
            options={
                'verbose_name': 'Personen-Zuordnung',
                'verbose_name_plural': 'Personen-Zuordnungen',
                'unique_together': {('item', 'person')},
            },
        ),
    ]
