# Generated by Django 6.0.5 on 2026-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_listitem_involved_persons_itempersonrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='involved_persons',
            field=models.ManyToManyField(blank=True, related_name='items', through='core.ItemPersonRole', to='core.person'),
        ),
    ]
