# Generated by Django 6.0.5 on 2026-05-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_listitem_involved_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Für wen ist diese Liste? (z.B. Geburtstagskind)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_lists', to='core.person'),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='is_secret_santa',
            field=models.BooleanField(default=False, help_text='Versteckt Zuordnungen vor dem Begünstigten'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itempersonrole',
            name='role',
            field=models.CharField(choices=[('assigned', 'Zuständig'), ('invited', 'Eingeladen'), ('attending', 'Zugesagt'), ('declined', 'Abgesagt'), ('maybe', 'Vielleicht'), ('reserved', 'Reserviert'), ('fulfilled', 'Wunsch erfüllt')], default='assigned', max_length=20),
        ),
    ]
