# Generated by Django 6.0.5 on 2026-05-17 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bucketlist_beneficiary_bucketlist_is_secret_santa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='ListParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_sent', models.BooleanField(default=False)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.bucketlist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_in', to='core.person')),
            ],
            options={
                'verbose_name': 'Listen-Teilnehmer',
                'verbose_name_plural': 'Listen-Teilnehmer',
                'unique_together': {('bucket_list', 'person')},
            },
        ),
    ]
