# Generated by Django 6.0.5 on 2026-05-17 14:06

import uuid
from django.db import migrations, models

def gen_unique_uuids(apps, schema_editor):
    Person = apps.get_model('core', 'Person')
    for person in Person.objects.all():
        person.access_token = uuid.uuid4()
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_person_access_token_listparticipant'),
    ]

    operations = [
        migrations.RunPython(gen_unique_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
