# Generated by Django 6.0.5 on 2026-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_person_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_rating',
            field=models.BooleanField(default=False),
        ),
    ]
