# Generated by Django 6.0.5 on 2026-05-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listitem_rating_listtemplate_use_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='tracker_dosage_per_take',
            field=models.FloatField(default=1.0, help_text='Verbrauch pro Abhaken'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='tracker_stock_min',
            field=models.IntegerField(blank=True, help_text='Warnschwelle für Nachbestellung', null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='tracker_stock_total',
            field=models.IntegerField(blank=True, help_text='Aktueller Gesamtbestand im Kasten/Packung', null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='tracker_times',
            field=models.CharField(blank=True, help_text='Komma-separierte Uhrzeiten, z.B. 08:00, 18:00', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='tracker_unit',
            field=models.CharField(blank=True, help_text='Einheit, z.B. Tablette, Portion, ml', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_tracker',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemTrackerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('scheduled_time', models.CharField(max_length=5)),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_logs', to='core.listitem')),
            ],
            options={
                'verbose_name': 'Tracker-Protokoll',
                'verbose_name_plural': 'Tracker-Protokolle',
                'unique_together': {('item', 'date', 'scheduled_time')},
            },
        ),
    ]
