# Generated by Django 6.0.5 on 2026-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_listitem_tracker_dosage_per_take_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
