# Generated by Django 6.0.5 on 2026-05-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_listitem_end_date_alter_listitem_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='target_milestone',
            field=models.CharField(blank=True, choices=[('before_30', 'Vor 30'), ('before_40', 'Vor 40'), ('before_50', 'Vor 50'), ('before_die', 'Bevor ich sterbe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
