# Generated by Django 6.0.5 on 2026-05-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_listitem_completed_at_listitem_target_milestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='target_milestone',
            field=models.CharField(blank=True, choices=[('before_30', 'Vor 30'), ('before_40', 'Vor 40'), ('before_50', 'Vor 50'), ('before_60', 'Vor 60'), ('before_die', 'Bevor ich sterbe')], max_length=20, null=True),
        ),
    ]
