# Generated by Django 6.0.5 on 2026-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_listitem_target_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtemplate',
            name='help_example',
            field=models.TextField(blank=True, help_text='📝 Praxis-Beispiel für einen Eintrag', null=True),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='help_fields',
            field=models.TextField(blank=True, help_text='🛠️ Welche Felder aktiv sind und wie man sie nutzt', null=True),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='help_purpose',
            field=models.TextField(blank=True, help_text='💡 Zweck der Vorlage (z.B. Ideal für den Wocheneinkauf)', null=True),
        ),
    ]
