# Generated by Django 6.0.5 on 2026-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_listtemplate_help_example_listtemplate_help_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=50),
        ),
    ]
