# Generated by Django 6.0.5 on 2026-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_usersetting_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='todo_sync_url',
            field=models.URLField(blank=True, help_text='Öffentlicher iCal/ICS-Link zur Synchronisation (z.B. Microsoft To-Do)', null=True, verbose_name='Microsoft To-Do iCal-Link'),
        ),
    ]
