# Generated by Django 6.0.5 on 2026-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_bucketlist_todo_sync_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtemplate',
            name='logic_type',
            field=models.CharField(choices=[('generic', 'Allgemein (Standard)'), ('todo', 'To-Do Liste'), ('gift', 'Geschenkeliste'), ('bucket', 'Bucketliste'), ('event', 'Veranstaltungsplaner'), ('tracker', 'Tracker / Gewohnheiten')], default='generic', help_text='Bestimmt den spezifischen Workflow für diesen Listentyp', max_length=20),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_allow_public_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='use_secret_santa',
            field=models.BooleanField(default=False),
        ),
    ]
