# Generated by Django 6.0.5 on 2026-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_listtemplate_logic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='calendar_end_hour',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='calendar_filter_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='calendar_filter_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='calendar_filter_tracker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='calendar_start_hour',
            field=models.IntegerField(default=8),
        ),
    ]
