# Generated by Django 6.0.5 on 2026-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_usersetting_calendar_end_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='calendar_refresh_interval',
            field=models.CharField(default='PT15M', max_length=10),
        ),
    ]
