# Generated by Django 6.0.5 on 2026-05-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_usersetting_calendar_refresh_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='workout_config_json',
            field=models.JSONField(blank=True, help_text='Konfiguration für Sätze, Distanzen, Intervalle', null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Krafttraining (Gewichte/Sätze)'), ('endurance', 'Ausdauertraining (Distanz/Zeit)'), ('interval', 'Intervalltraining (Crossfit/HIIT)')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gym_body_measurements_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gym_fitness_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gym_nutrition_plan_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gym_plan_adaptation_message',
            field=models.TextField(default='Bitte melde dich beim Trainer für einen neuen Plan, damit die Fortschritte möglich sind.'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gym_plan_adaptation_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gym_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listtemplate',
            name='logic_type',
            field=models.CharField(choices=[('generic', 'Allgemein (Standard)'), ('todo', 'To-Do Liste'), ('gift', 'Geschenkeliste'), ('bucket', 'Bucketliste'), ('event', 'Veranstaltungsplaner'), ('tracker', 'Tracker / Gewohnheiten'), ('workout', 'Trainingsplan / Sport')], default='generic', help_text='Bestimmt den spezifischen Workflow für diesen Listentyp', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkoutSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='core.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainingseinheit Protokoll',
                'verbose_name_plural': 'Trainingseinheiten Protokolle',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=20)),
                ('logged_data_json', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.workoutsessionlog')),
            ],
            options={
                'verbose_name': 'Aktivität Protokoll',
                'verbose_name_plural': 'Aktivitäten Protokolle',
            },
        ),
    ]
