# Generated by Django 6.0.5 on 2026-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_listitem_workout_config_json_listitem_workout_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='header_bg_color',
            field=models.CharField(default='#543D62', max_length=7),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='header_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
