# Generated by Django 6.0.5 on 2026-05-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usersetting_header_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='alexa_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Alexa User ID'),
        ),
    ]
