# Generated by Django 6.0.5 on 2026-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_usersetting_alexa_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Subdomain-Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Instanz-Name')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Besitzer-E-Mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Mandant',
                'verbose_name_plural': 'Mandanten',
            },
        ),
    ]
