# Generated by Django 6.0.5 on 2026-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='is_invitation',
            field=models.BooleanField(default=False, verbose_name='Ist eine Einladung'),
        ),
    ]
