# Generated by Django 6.0.5 on 2026-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_listitem_is_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='accent_color',
            field=models.CharField(default='#4eb422', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='bg_color',
            field=models.CharField(default='#1f1325', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='glass_opacity',
            field=models.DecimalField(decimal_places=2, default=0.11, max_digits=3),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='header_bg_color',
            field=models.CharField(default='#543d62', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='input_bg_color',
            field=models.CharField(default='#614190', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='input_text_color',
            field=models.CharField(default='#fde5ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='primary_color',
            field=models.CharField(default='#e1d7ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='text_color',
            field=models.CharField(default='#d3f5d1', max_length=7),
        ),
    ]
