# Generated by Django 6.0.5 on 2026-05-24 18:56

import re
from decimal import Decimal, InvalidOperation
from django.db import migrations

def seed_units_and_parse_amounts(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    
    Unit = apps.get_model('core', 'Unit')
    ListItem = apps.get_model('core', 'ListItem')
    
    # 1. Seed default units
    default_units = [
        ('stk.', 'stk'),
        ('Fl.', 'flaschen'),
        ('l', 'l'),
        ('g', 'g'),
        ('kg', 'kg'),
        ('m', 'm'),
        ('cm', 'cm'),
    ]
    
    for name, slug in default_units:
        if not Unit.objects.using(db_alias).filter(slug=slug).exists():
            Unit.objects.using(db_alias).create(name=name, slug=slug)

    # 2. Iterate and parse amounts of existing ListItems
    for item in ListItem.objects.using(db_alias).all():
        if not item.amount:
            continue
            
        s = item.amount.strip()
        match = re.match(r'^([\d\.,]+)\s*(.*)$', s)
        if not match:
            # Not parseable as leading number: keep it in text amount, amount_value stays None
            continue
            
        num_str, unit_str = match.groups()
        num_str = num_str.replace(',', '.')
        
        try:
            val = Decimal(num_str)
        except (InvalidOperation, ValueError):
            continue
            
        unit_clean = unit_str.strip().lower()
        unit_slug = None
        unit_name = None
        
        if unit_clean in ['stk', 'stück', 'stueck', 'x']:
            unit_slug = 'stk'
            unit_name = 'stk.'
        elif unit_clean in ['flaschen', 'flasche', 'fl']:
            unit_slug = 'flaschen'
            unit_name = 'Fl.'
        elif unit_clean in ['l', 'liter']:
            unit_slug = 'l'
            unit_name = 'l'
        elif unit_clean in ['g', 'gramm']:
            unit_slug = 'g'
            unit_name = 'g'
        elif unit_clean in ['kg', 'kilo', 'kilogramm']:
            unit_slug = 'kg'
            unit_name = 'kg'
        elif unit_clean in ['m', 'meter']:
            unit_slug = 'm'
            unit_name = 'm'
        elif unit_clean in ['cm', 'zentimeter']:
            unit_slug = 'cm'
            unit_name = 'cm'
        elif unit_clean:
            # Fallback for custom units
            from django.utils.text import slugify
            unit_slug = slugify(unit_clean)[:50]
            unit_name = unit_str.strip()
            
        # Bind unit and save
        item.amount_value = val
        if unit_slug:
            unit_obj, _ = Unit.objects.using(db_alias).get_or_create(
                slug=unit_slug,
                defaults={'name': unit_name or unit_clean}
            )
            item.unit = unit_obj
            
        item.save(using=db_alias)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_unit_listitem_amount_value_listitem_unit'),
    ]

    operations = [
        migrations.RunPython(seed_units_and_parse_amounts, migrations.RunPython.noop),
    ]
