# Generated by Django 6.0.5 on 2026-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20260524_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtemplate',
            name='new_items_at_bottom',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden neue Einträge am Ende der Liste angefügt, andernfalls oben.', verbose_name='Neue Einträge unten anfügen'),
        ),
    ]
